name: Security Alert Bot

on:
  schedule:
    - cron: '30 23 * * *' # 한국 시간 오전 8시 30분 (UTC 23:30)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Bot
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        LAW_API_KEY: ${{ secrets.LAW_API_KEY }}
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
      run: python main.py